// vue-todo/src/App.vue
<template>
	<section>
		<div v-if="loggedIn">
			<navbar @logout="logout"></navbar>
			<profile
				:displayName="this.user.displayName"
				:photoURL="this.user.photoURL"
			></profile>
      <hr />
			<todos :uid="this.user.uid"></todos>
		</div>
		<button v-else type="button" class="btn btn-dark" @click="login">
			Google Signin
		</button>
	</section>
</template>

<script>
import Navbar from "./Navbar";
import Profile from "./Profile";
import Todos from "./Todos";
import { auth, googleProvider } from "./firebase";
import { authState } from "rxfire/auth";

export default {
	components: {
		Navbar,
		Profile,
		Todos,
	},
	data() {
		return {
			user: null,
		};
	},
	created() {
		auth.onAuthStateChanged(u => {
			this.user = u;
		});
	},
	methods: {
		login() {
			auth.signInWithPopup(googleProvider);
		},
		logout() {
			auth.signOut();
		},
	},
	computed: {
		loggedIn() {
			return this.user !== null;
		},
	},
};
</script>

<style></style>

// react-todo/src/App.js
import React from "react";
import { useState } from "react";
import { auth, googleProvider } from "./firebase";
import { authState } from "rxfire/auth";

import Navbar from "./Navbar";
import Profile from "./Profile";
import Todos from "./Todos";

const App = () => {
	const [user, setUser] = useState(null);

	authState(auth).subscribe(u => setUser(u));

	const login = () => {
		auth.signInWithPopup(googleProvider);
	};

	const logout = () => {
		auth.signOut();
	};

	return (
		<section>
			{user ? (
				<div>
					<Navbar logout={logout} />
					<Profile {...user} />
					<hr />
					<Todos uid={user.uid} />
				</div>
			) : (
				<button type="button" className="btn btn-dark" onClick={login}>
					Google Signin
				</button>
			)}
		</section>
	);
};

export default App;
