// vue-todo/src/TodoItem.vue
<template>
	<tr>
		<th scope="row">{{ index }}</th>
		<td v-if="complete" class="table-success text-center">
			<span class="is-complete">{{ text }}</span>
		</td>
		<td v-else class="text-center">
			<span>{{ text }}</span>
		</td>
		<td class="text-center">
			<button
				v-if="!complete"
				title="Complete"
				v-on:click="$emit('toggle', { id, newStatus })"
			>
				✔️
			</button>
			<button
				v-else
				title="Undo"
				v-on:click="$emit('toggle', { id, newStatus })"
			>
				❌
			</button>
		</td>
		<td class="text-center">
			<button title="Remove" v-on:click="$emit('remove', id)">🗑</button>
		</td>
	</tr>
</template>

<script>
export default {
	props: {
		index: Number,
		id: String,
		text: String,
		complete: Boolean,
	},
	computed: {
		newStatus() {
			return !this.complete;
		},
	},
};
</script>

<style>
.is-complete {
	text-decoration: line-through;
}
.text-center {
	text-align: center;
}
</style>

// svelte-todo/src/TodoItem.svelte
<script>
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  export let index;
  export let id;
  export let text;
  export let complete;

  const remove = () => {
    dispatch("remove", { id })
  }

  const toggleStatus = () => {
    let newStatus = !complete;
    dispatch("toggle", {
      id,
      newStatus
    });
  }
</script>

<style>
  .is-complete {
    text-decoration: line-through;
  }
  .text-center {
    text-align: center
  }
</style>

<tr>
  <th scope="row">{index}</th>
  {#if complete}
    <td class="table-success text-center">
      <span class="is-complete">{text}</span>
    </td>
  {:else}
    <td class="text-center"><span>{text}</span></td>
  {/if}
  <td class="text-center">
    {#if !complete}
      <button  title="Complete" on:click={toggleStatus}>✔️</button>
    {:else}
      <button  title="Undo" on:click={toggleStatus}>❌</button>
    {/if}
  </td>
  <td class="text-center">
    <button  title="Remove" on:click={remove}>🗑</button>
  </td>
</tr>
