// vue-todo/src/Todos.vue
<template>
	<div>
		<table class="table table-striped table-bordered table-hover">
			<caption>
				List of TODOs
			</caption>
			<thead class="thead-dark">
				<tr>
					<th scope="col">Task No.</th>
					<th scope="col">Complete</th>
					<th scope="col">Action</th>
					<th scope="col">Remove</th>
				</tr>
			</thead>
			<tbody>
				<TodoItem
					v-for="(todo, index) in todos"
					:key="index"
					:index="index"
					:id="todo.id"
					:text="todo.text"
					:complete="todo.complete"
					@remove="removeItem"
					@toggle="updateStatus"
				/>
			</tbody>
		</table>
		<input type="text" v-model="text" placeholder="Enter todo..." />
		<button type="button" class="btn btn-dark" @click="add">Add Task</button>
	</div>
</template>

<script>
import TodoItem from "./TodoItem";
import { db } from "./firebase";

export default {
	name: "todos",
	props: {
		uid: String,
	},
	components: {
		TodoItem,
	},
	data() {
		return {
			text: "",
			todos: [],
		};
	},
	created() {
		db.collection("todos")
			.where("uid", "==", this.uid)
			.orderBy("created")
			.onSnapshot(snapshot => {
				const todos = [];
				snapshot.forEach(doc => {
					todos.push({
						...doc.data(),
						id: doc.id,
					});
				});
				this.todos = todos;
			});
	},
	methods: {
		data() {
			return {
				text: "",
			};
		},
		add() {
			let uid = this.uid;
			let text = this.text;
			db.collection("todos").add({
				uid,
				text,
				complete: false,
				created: Date.now(),
			});
			this.text = "";
		},
		removeItem(id) {
			db.collection("todos")
				.doc(id)
				.delete();
		},
		updateStatus({ id, newStatus }) {
			db.collection("todos")
				.doc(id)
				.update({ complete: newStatus });
		},
	},
};
</script>

<style>
input {
	display: block;
}
th {
	text-align: left;
}
</style>

// svelte-todo/src/Todos.svelte
<script>
  import TodoItem from "./TodoItem.svelte";
  import { db } from "./firebase.js";
  import { collectionData } from "rxfire/firestore";
  import { startWith } from "rxjs/operators";

  export let uid;
  let text = "";

  const query = db
    .collection("todos")
    .where("uid", "==", uid)
    .orderBy("created");

  const todos = collectionData(query, "id").pipe(startWith([]));

  const add = () => {
    db.collection("todos").add({
      uid,
      text,
      complete: false,
      created: Date.now()
    });
    text = "";
  }

  const updateStatus = (event) => {
    const { id, newStatus } = event.detail;
    db.collection("todos")
      .doc(id)
      .update({ complete: newStatus });
  }

  const removeItem = (event) => {
    const { id } = event.detail;
    db.collection("todos")
      .doc(id)
      .delete();
  }
</script>

<style>
  input {
    display: block;
  }
  th {
    text-align: left;
  }
</style>

<table class="table table-striped table-bordered table-hover">
  <caption>List of TODOs</caption>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Task No.</th>
      <th scope="col">Complete</th>
      <th scope="col">Action</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
    {#each $todos as todo, index}
      <TodoItem
        {index}
        {...todo}
        on:remove={removeItem}
        on:toggle={updateStatus} />
    {/each}
  </tbody>
</table>

<input type="text" bind:value={text} placeholder="Enter todo..." />

<button type="button" class="btn btn-dark" on:click={add}>Add Task</button>
